version: "3"
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data

  wait_for_db:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432

  tomcat8:
    depends_on:
      - wait_for_db
    image: tomcat:alpine
    ports:
      - 8080:8080
      - 80:8080
      - 443:8443
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    environment:
      VIRTUAL_HOST: odk-aggregate.amed-bu.com
      LETSENCRYPT_HOST: odk-aggregate.amed-bu.com
      LETSENCRYPT_EMAIL: ntds.team@gmail.com
      AGGREGATE_HOST: odk-aggregate.amed-bu.com
  proxy:
    image: jwilder/nginx-proxy
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-compose.d/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    privileged: true
    volumes:
      - ./docker-compose.d/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy
